In [223]:
import pandas as pd
import numpy as np

In [224]:
numpy.version.version

'1.18.5'

In [225]:
pd.__version__

'1.0.5'

In [226]:
df=pd.read_csv('data.csv')

In [227]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [228]:
df.rename(columns={'Engine HP': 'Engine_HP'},inplace=True)

In [229]:
print('average price of BMW is',df[df['Make']=="BMW"].MSRP.mean())


average price of BMW is 61546.76347305389


In [230]:
b=df[df['Year']>=2015].Engine_HP.isnull().sum()
print('number of missing value of Engine HP after 2015 is',b)

number of missing value of Engine HP after 2015 is 51


In [231]:
mean_hp_before=df['Engine_HP'].mean()
print('mean before fillna',round(mean_hp_before))

mean before fillna 249


In [232]:
mean_hp_after=df['Engine_HP'].fillna(df['Engine_HP'].mean()).mean()
print('mean after fillna',round(mean_hp_after))

mean after fillna 249


In [233]:
RollRoyce=df[df['Make']=='Rolls-Royce']
df_new=RollRoyce[['Engine_HP','Engine Cylinders','highway MPG',]]

In [234]:
df_drop=df_new.drop_duplicates()

In [235]:
X=df_drop.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [236]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [237]:
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [238]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [239]:
XTXinv.sum()

0.03221232067748617

In [240]:
y=np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [244]:
X_new = XTXinv.dot(XT)
X_new

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [246]:
w = X_new.dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])